# Generated by Django 6.0.1 on 2026-01-13 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备ID')),
                ('device_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备类型')),
                ('device_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备编码')),
                ('local_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='本地IP')),
                ('local_port', models.IntegerField(blank=True, null=True, verbose_name='本地端口')),
                ('proxy_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='代理IP')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'rpa_device',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.IntegerField(blank=True, choices=[(0, '未分类'), (1, '女士'), (2, '宠物'), (3, '婴儿')], null=True, verbose_name='标签类型')),
                ('search_word', models.TextField(blank=True, null=True, verbose_name='搜索词汇')),
            ],
            options={
                'verbose_name': '搜索词汇',
                'verbose_name_plural': '搜索词汇',
                'db_table': 'rpa_search_word',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TikTokAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备ID')),
                ('tiktok_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='TK账号')),
                ('account_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='TK密码')),
                ('account_tag', models.IntegerField(blank=True, choices=[(0, '未分类'), (1, '女士'), (2, '宠物'), (3, '婴儿')], null=True, verbose_name='账号标签')),
                ('account_status', models.IntegerField(blank=True, choices=[(0, '正常'), (1, '封号'), (2, '养号')], null=True, verbose_name='状态')),
                ('account_likes', models.IntegerField(blank=True, null=True, verbose_name='点赞数')),
                ('account_followers', models.IntegerField(blank=True, null=True, verbose_name='关注数')),
                ('account_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机号')),
                ('account_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('mail_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱密码')),
                ('account_momo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账号信息',
                'verbose_name_plural': '账号信息',
                'db_table': 'rpa_tiktok_account_info',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='视频路径')),
                ('video_tag', models.IntegerField(blank=True, choices=[(0, '未分类'), (1, '女士'), (2, '宠物'), (3, '婴儿')], default=0, null=True, verbose_name='视频标签')),
                ('status', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='视频状态')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'db_table': 'rpa_video',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_content', models.CharField(blank=True, max_length=256, null=True, verbose_name='文案内容')),
                ('copy_tag', models.IntegerField(blank=True, choices=[(0, '未分类'), (1, '女士'), (2, '宠物'), (3, '婴儿')], null=True, verbose_name='文案标签')),
                ('status', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='文案状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频文案',
                'verbose_name_plural': '视频文案',
                'db_table': 'rpa_video_copy',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiktok_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='TikTok账号')),
                ('video_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='视频ID')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='视频描述')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频数据',
                'verbose_name_plural': '视频数据',
                'db_table': 'rpa_video_data',
                'ordering': ['-create_date'],
            },
        ),
    ]
