# Generated by Django 6.0.1 on 2026-01-12 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备ID')),
                ('tiktok_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='TK账号')),
                ('account_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='TK密码')),
                ('account_tag', models.IntegerField(blank=True, null=True, verbose_name='账号标签')),
                ('account_status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('account_likes', models.IntegerField(blank=True, null=True, verbose_name='点赞数')),
                ('account_followers', models.IntegerField(blank=True, null=True, verbose_name='关注数')),
                ('account_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机号')),
                ('account_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('mail_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱密码')),
                ('account_momo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TikTok账号信息',
                'verbose_name_plural': 'TikTok账号信息',
                'db_table': 'rpa_tiktok_account_info',
                'ordering': ['-create_date'],
            },
        ),
    ]
