# Generated by Django 6.0.1 on 2026-01-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备ID')),
                ('device_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备类型')),
                ('device_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备编码')),
                ('local_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='本地IP')),
                ('local_port', models.IntegerField(blank=True, null=True, verbose_name='本地端口')),
                ('proxy_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='代理IP')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'rpa_device',
                'ordering': ['id'],
            },
        ),
    ]
