# Generated by Django 6.0.1 on 2026-01-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='视频路径')),
                ('video_tag', models.IntegerField(blank=True, default=0, null=True, verbose_name='视频标签')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'db_table': 'rpa_video',
                'ordering': ['id'],
            },
        ),
    ]
