# Generated by Django 6.0.1 on 2026-01-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_content', models.CharField(blank=True, max_length=256, null=True, verbose_name='文案内容')),
                ('copy_tag', models.IntegerField(blank=True, null=True, verbose_name='文案标签')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='文案状态')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频文案',
                'verbose_name_plural': '视频文案',
                'db_table': 'rpa_video_copy',
                'ordering': ['id'],
            },
        ),
    ]
