# Generated by Django 6.0.1 on 2026-01-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_video_video_tag_alter_videocopy_copy_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokaccountinfo",
            name="account_tag",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未分类"),
                    (1, "女士"),
                    (2, "宠物"),
                ],
                null=True,
                verbose_name="账号标签",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_tag",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未分类"),
                    (1, "女士"),
                    (2, "宠物"),
                ],
                default=0,
                null=True,
                verbose_name="视频标签",
            ),
        ),
        migrations.AlterField(
            model_name="videocopy",
            name="copy_tag",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未分类"),
                    (1, "女士"),
                    (2, "宠物"),
                    (3, "美食"),
                ],
                null=True,
                verbose_name="文案标签",
            ),
        ),
    ]
